### ISSUE TITLE
128mb vram now required?

### ISSUE THREAD

**Issue by brthornbury** [geerlingguy/macos-virtualbox-vm#16]
I was unable to get the VM past a black screen without increasing vram all the way to 128mb. 

Even tried 64mb. 

Not sure if this is a consistent issue but sticking this here in case other folks run into this.

**Comment by MrGrinst** [comment]
+1

**Comment by PatrickJD** [comment]
I had this issue as well, setting to 128 mb resolved for me as well.

**Comment by geerlingguy** [comment]
@brthornbury @MrGrinst @PatrickJD - Thanks for the +1s here, I've added a note in the README in the above commit!
