### ISSUE TITLE
How may one download the image on a non-macos box?

### ISSUE THREAD

**Issue by kathiedart** [geerlingguy/macos-virtualbox-vm#18]
Can the tutorial be updated to allow downloading the image on a box without macos? I think many use cases would require not already having macos.
Cheers

**Comment by geerlingguy** [comment]
That's likely against the Apple's license agreement, so I definitely couldn't support it 'officially', but I do know there have been many attempts through the years to get an OS X image running on Windows (e.g. http://www.macbreaker.com/2014/05/os-x-mavericks-in-virtualbox-with-niresh.html).

This project does not aim to build a portable box file that can be used on any platform, only to build VMs for macOS testing within a macOS VirtualBox environment.

**Comment by kathiedart** [comment]
Gotcha, alright *glues Apple sticker on laptop*

**Comment by geerlingguy** [comment]
Haha! Now it's a Mac :D
