### ISSUE TITLE
Higher Resolution? Lag?

### ISSUE THREAD

**Issue by HenryDev** [geerlingguy/macos-virtualbox-vm#20]
Is there any way to increase the resolution past option 5 to 2560x1440?

Also there's a lot of lag on display, especially when dragging or resizing windows. Is there a way to reduce lag?

**Comment by PatrickJD** [comment]
@HenryDev I've tried running n=6 and higher but the resolution does not change from 1920x1200.  I believe this is a limitation of VirtualBox.  You can try assigning more video RAM if your host system is powerful enough.  Note, you cannot assign more than 128MB in the GUI, you will need to use the following command line:

VBoxManage modifyvm "Name of VM" --vram 256

**Comment by HenryDev** [comment]
Thanks that's good to know
