### ISSUE TITLE
"Failed to mount the InstallESD.dmg" Error

### ISSUE THREAD

**Issue by xd1936** [geerlingguy/macos-virtualbox-vm#21]
Hello!

I'm running a fresh copy of Sierra and a fresh download of the Sierra installer (10.12.3) in my Applications directory. When I run this script, I get the following error: 

```
Mount the installer image
-----------------------------------------------------------
$ hdiutil attach /Applications/Install macOS Sierra.app/Contents/SharedSupport/InstallESD.dmg -noverify -nobrowse -mountpoint /Volumes/install_app
hdiutil: attach failed - Resource busy
Failed to mount the InstallESD.dmg from the instaler at Install macOS Sierra.app.  Exiting. (1)
```

Any thoughts?

**Comment by xd1936** [comment]
Oh.

I went into Disk Utility and unmounted the image, and the script worked great. 🤦‍♂️

**Comment by geerlingguy** [comment]
@xd1936 - No problem, I'm happy you posted the issue and solution, at least—future Google searches will thank you :)

**Comment by dbackeus** [comment]
True that :)

Thanks!

**Comment by tuchido** [comment]
It worked.

Thanks!
