### ISSUE TITLE
discouraging use of option -r with cp(1)

### ISSUE THREAD

**Issue by grahamperrin** [geerlingguy/macos-virtualbox-vm#31]
From Apple's legacy [cp(1) Mac OS X Manual Page](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/cp.1.html): 

> **COMPATIBILITY**
> 
> Historic versions of the **`cp`** utility had a **`-r`** option.  This implementation supports that option; however, its use is strongly discouraged, as it does not correctly copy special files, symbolic links, or fifo's.
> 
> The **`-v`** and **`-n`** options are non-standard and their use in scripts is not recommended.

– (sic; should be _fifos_ (not _fifo's_)). The same discouragement appears in the manual page for `cp(1)` in pre-release build 17A264c of Mac OS X 10.13. 

Please: 

- does anyone know of a good reason for the use of `-r` in `prepare-iso.sh`? 

(I sped through some of the documentation that's referred from `README.md`, found no explanation.)

**Comment by robbintt** [comment]
I have always been interested in this so I looked for an answer. Here is what I found. 

https://unix.stackexchange.com/questions/18712/difference-between-cp-r-and-cp-r-copy-command

It appears that it all comes down to posix and those should be changed to "-R".

Best,
Trent

**Comment by geerlingguy** [comment]
Yeah, `-r` was probably just fat-fingered on my part. I think they should be `-R`.

**Comment by grahamperrin** [comment]
Thank you both. 

@robbintt yeah, I glanced at the same page before posting here. 

@geerlingguy re: https://github.com/geerlingguy/macos-virtualbox-vm/issues/28#issuecomment-309231703 alternatively there's `ditto(8)`.

**Comment by geerlingguy** [comment]
The `-r` option isn't even mentioned in the official `cp` man pages anymore. Will commit a fix in a few.
