### ISSUE TITLE
Setup documentation terminology

### ISSUE THREAD

**Issue by ghost** [geerlingguy/macos-virtualbox-vm#33]
The readme.md specifies using the dropdown to select `macOS Sierra, if your version of VirtualBox has been updated to include it`

on 5.1.22 the latest selection is El Capitan, leading me to use `Mac OS X (64 bit)` - is there a beta version somewhere or was this said to "future-proof" the documentation? Is there any problem using this generic selection of `Mac OS X (64 bit)` for all installations? Does anyone know is a difference in specifying the exact version?

Thanks 😄

**Comment by geerlingguy** [comment]
Pushed a commit to update the terms used to match the current version of VirtualBox (5.2.16).
