### ISSUE TITLE
El Capitan guest, Sierra host, VB 5.2.2 r119230 -> "invalid opcode" error when trying to boot

### ISSUE THREAD

**Issue by magicgoose** [geerlingguy/macos-virtualbox-vm#45]
Got `Install OS X El Capitan.app` at 9th December 2017 (yesterday at the time of writing) from mac app store. Installer has version `1.7.50`.

Made the .iso file from it by using the script from this repository. Resulting file size = 8015142912 bytes and its sha256 sum is `4c8f512b963a29f48b34552cca75c789a8fc14d1413dd0a4549e5817a6465355`.

Created VirtualBox VM as described in README (incl. the cpuid step), then tried to boot it, and it only reaches a panic state with an "invalid opcode" error. (full screenshot below)

![virtualbox_osx_10_12_2017_09_46_06](https://user-images.githubusercontent.com/1442206/33803046-3dc152c6-dd8f-11e7-96d9-fff4a5d5893f.png)

What could go wrong?

**Comment by magicgoose** [comment]
Changed OS in VM preferences from El Capitan to "just" OS X 64-bit, and it seems to solve it.

**Comment by kuhouin-murasaki** [comment]
> Changed OS in VM preferences from El Capitan to "just" OS X 64-bit, and it seems to solve it.

also working for High Sierra host and Sierra guest
