### ISSUE TITLE
hdiutil command does not exist on Fedora 27

### ISSUE THREAD

**Issue by phracek** [geerlingguy/macos-virtualbox-vm#50]
I am trying to install macOSSierra on my Fedora 27 machine, but `hdiutil` does not exist.
Do you have a solution for it?
~~~
$ ./prepare-iso.sh 
./prepare-iso.sh: line 143: hdiutil: command not found
xargs: hdiutil: No such file or directory
Could not find installer for Yosemite (10.10), El Capitan (10.11) or Sierra (10.12).
$ uname -a
Linux auris.stone 4.16.7-200.fc27.x86_64 #1 SMP Wed May 2 20:33:31 UTC 2018 x86_64 x86_64 
$ cat /etc/redhat-release 
Fedora release 27 (Twenty Seven)
$ 


~~~

**Comment by qrkourier** [comment]
I ran in to this problem too and I suspect the script was written for BASH on Darwin Unix only.

**Comment by geerlingguy** [comment]
Yeah, this script is only meant for macOS / Darwin... there are a lot of little bits that will break on Linux/non-macOS environments. Technically you could build the iso on a Mac then move it to a non-Mac... but that is untested, technically outside the scope of the macOS license, and unsupported by this project ;)
