### ISSUE TITLE
VirtualBox with High-Sierra fails,  "Attempting system restart...MACH Reboot" or repeating reboots

### ISSUE THREAD

**Issue by mwaeckerlin** [geerlingguy/macos-virtualbox-vm#52]
VirtualBox: tried with two versions:
- 5.2.10-dfsg-6 from Ubuntu 18.04
- 5.2.18 r124319 (Qt5.9.5), latest from http://download.virtualbox.org/virtualbox/debian/pool/contrib/v/virtualbox-5.2/

One thing is new: Now VirtualBox pretends to explicitely support `macOS 10.13 High Sierra (64bit)`:
![grafik](https://user-images.githubusercontent.com/4056726/45142866-ea229080-b1b9-11e8-9b55-bd437ccaefe9.png)

Information in `README.md` is outdated:

> If for High Sierra you encounter boot / EFI problems, restart the VM and hit F12 to get to the VirtualBox boot manager. Select EFI In-Terminal Shell and run:
> 
>   ```bash
>   Shell> fs1:
>   FS1:\> cd "macOS Install Data"
>   FS1:\macOS Install Data\> cd "Locked Files"
>   FS1:\macOS Install Data\Locked Files\> cd "Boot Files"
>   FS1:\macOS Install Data\Locked Files\Boot Files\> boot.efi
>   ```

Neither drive (`fs1:`) nor path (`macOS Install Data`) exists:

![virtualbox_mac os x high sierra - failed_06_09_2018_09_18_56](https://user-images.githubusercontent.com/4056726/45141664-ca3d9d80-b1b6-11e8-853f-50bd9b56c7e1.png)

I tried according to the documentation and ended with `Attempting system restart...MACH Reboot`, see snapshots from the screen-video:

![vlcsnap-2018-09-06-09h31m52s073](https://user-images.githubusercontent.com/4056726/45142048-cbbb9580-b1b7-11e8-8ad2-5b3262b85256.png)
![vlcsnap-2018-09-06-09h32m04s182](https://user-images.githubusercontent.com/4056726/45142057-cfe7b300-b1b7-11e8-9e50-d40dbe0bf28f.png)
![vlcsnap-2018-09-06-09h33m21s439](https://user-images.githubusercontent.com/4056726/45142110-f73e8000-b1b7-11e8-9b75-50e510c0f32b.png)
![vlcsnap-2018-09-06-09h33m35s536](https://user-images.githubusercontent.com/4056726/45142122-fc9bca80-b1b7-11e8-8411-de33bf07566e.png)
![vlcsnap-2018-09-06-09h33m44s595](https://user-images.githubusercontent.com/4056726/45142133-07565f80-b1b8-11e8-9e25-037f5513172e.png)

Next I tried a new image without the CPU-patch, so I did not enter the following command:

> 7. In Terminal, run the command `VBoxManage modifyvm VM_NAME --cpuidset 00000001 000306a9 00020800 80000201 178bfbff` (where `VM_NAME` is the exact name of the VM set in step 4) so the VM has the right CPU settings for macOS.

It then goes further, but still fails and constantly reboots, here some screenshots from the video:

![vlcsnap-2018-09-06-09h38m09s412](https://user-images.githubusercontent.com/4056726/45142487-0114b300-b1b9-11e8-84ee-b47ef88de6e1.png)
![vlcsnap-2018-09-06-09h38m22s838](https://user-images.githubusercontent.com/4056726/45142492-03770d00-b1b9-11e8-8dec-a3f86487ae97.png)
![vlcsnap-2018-09-06-09h38m37s909](https://user-images.githubusercontent.com/4056726/45142498-0540d080-b1b9-11e8-9d02-191c1692b301.png)
![vlcsnap-2018-09-06-09h38m47s025](https://user-images.githubusercontent.com/4056726/45142503-07a32a80-b1b9-11e8-89b3-f373f6614913.png)
![vlcsnap-2018-09-06-09h38m56s149](https://user-images.githubusercontent.com/4056726/45142517-0c67de80-b1b9-11e8-92a9-22f8589b6331.png)
![vlcsnap-2018-09-06-09h39m03s730](https://user-images.githubusercontent.com/4056726/45142518-0d007500-b1b9-11e8-909a-db2c4b852ec0.png)
![vlcsnap-2018-09-06-09h39m11s153](https://user-images.githubusercontent.com/4056726/45142519-0d007500-b1b9-11e8-967d-8754c0d4b877.png)
![vlcsnap-2018-09-06-09h39m17s964](https://user-images.githubusercontent.com/4056726/45142520-0d007500-b1b9-11e8-9532-5f126268ce54.png)
![vlcsnap-2018-09-06-09h39m24s812](https://user-images.githubusercontent.com/4056726/45142521-0d990b80-b1b9-11e8-8cd3-f67485e11543.png)
![vlcsnap-2018-09-06-09h39m30s893](https://user-images.githubusercontent.com/4056726/45142522-0d990b80-b1b9-11e8-842d-0dfb48e27f93.png)
![vlcsnap-2018-09-06-09h39m38s940](https://user-images.githubusercontent.com/4056726/45142631-4a650280-b1b9-11e8-869b-0a9f4487899b.png)
![vlcsnap-2018-09-06-09h39m58s527](https://user-images.githubusercontent.com/4056726/45142658-581a8800-b1b9-11e8-99f4-619b9f3f96ef.png)
![vlcsnap-2018-09-06-09h40m11s407](https://user-images.githubusercontent.com/4056726/45142659-581a8800-b1b9-11e8-9bc3-ca3a7adc5eaa.png)
![vlcsnap-2018-09-06-09h40m23s550](https://user-images.githubusercontent.com/4056726/45142660-581a8800-b1b9-11e8-9f21-6b1d09e416dc.png)
![vlcsnap-2018-09-06-09h40m30s904](https://user-images.githubusercontent.com/4056726/45142661-581a8800-b1b9-11e8-9844-70bcd6c55d3b.png)
![vlcsnap-2018-09-06-09h40m36s522](https://user-images.githubusercontent.com/4056726/45142662-58b31e80-b1b9-11e8-87d6-c82cdb3fa842.png)

**Comment by mwaeckerlin** [comment]
GitHub does not allow to upload the videos directly, but I could upload them as ZIP, so sorry for the unneccessary extra package. These are the videos from where I took the screenshots above:

[Mac OS X High Sierra-2018-09-05T13-59-27-928531000Z.zip](https://github.com/geerlingguy/macos-virtualbox-vm/files/2356451/Mac.OS.X.High.Sierra-2018-09-05T13-59-27-928531000Z.zip)
[Mac OS X High Sierra - failed.zip](https://github.com/geerlingguy/macos-virtualbox-vm/files/2356454/Mac.OS.X.High.Sierra.-.failed.zip)

**Comment by xtmq** [comment]
The same thing for me...

**Comment by mwaeckerlin** [comment]
@crou, thank you, that solves the problem so far! Currently the installation is running.

Another problem I had:
- First go to the disk-tool to format the harddisk
- Then go to the installation
You can't setup the harddisk during the installation and you can't go back to the disk-tool without reboot…

Here for all to copy paste, it's the same as above from @crou, but with a variable for easier pasting:
```bash
VMNAME='Your VM name here'
VBoxManage modifyvm ${VMNAME} --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff
VBoxManage setextradata ${VMNAME} "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct" "iMac11,3"
VBoxManage setextradata ${VMNAME} "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion" "1.0"
VBoxManage setextradata ${VMNAME} "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct" "Iloveapple"
VBoxManage setextradata ${VMNAME} "VBoxInternal/Devices/smc/0/Config/DeviceKey" "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"
VBoxManage setextradata ${VMNAME} "VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC" 1
```

**Comment by terminatorul** [comment]
After setting the above EFI values on my Ubuntu, I got errors when starting the virtual machine: 

  Invalid config value(s) for the EFI device (VERR_PDM_DEVINS_UNKNOWN_CFG_VALUES).

The fix was to to add my user to group vboxusers, as it looks like on Ubuntu I was not a group member by default.
