### ISSUE TITLE
Unable to install High Sierra (no FS1)

### ISSUE THREAD

**Issue by nlsrchtr** [geerlingguy/macos-virtualbox-vm#58]
Hi @geerlingguy,

thanks for your time and effort you put together to make this work. It saved me a lot of time, but unfortunatly I'm stuck, right before it should all work. I tried all ways and also downgraded VirtualBox to _5.2.16 r123759_. I also experienced https://github.com/geerlingguy/macos-virtualbox-vm/issues/52 and used the solution from https://github.com/geerlingguy/macos-virtualbox-vm/issues/52#issuecomment-421266398.

After following your steps closely, I'm always stuck with a system, which is booting into "Recovery Mode", if I leave the DVD in place or I only see the following screen:

<img width="674" alt="bildschirmfoto 2018-11-18 um 21 14 49" src="https://user-images.githubusercontent.com/36688/48677771-18d5c380-eb7a-11e8-8c9b-0c1ac48e3e16.png">

Since there is no FS1, I think this issue is not related to https://github.com/geerlingguy/macos-virtualbox-vm/issues/53 and as you can see in the screenshot, there is data folder in FS0.

I'm wondering if someone could help me out here. I'm a little bit stuck here and would really like to bring High Sierra into VirtualBox to separate several tasks and processes for testing etc.

Thanks again for all the work and effort!

**Comment by daryllstrauss** [comment]
I had the same problem. Don't use APFS, use Mac OS Extended Journaled when you format your disk. It appears Virtualbox doesn't support APFS.

**Comment by nlsrchtr** [comment]
Thanks for helping out. I read about that at https://github.com/AlexanderWillner/runMacOSinVirtualBox and decided to give that a try. So I'm fine, running Mojave now on VirtualBox, they use Clover for booting, even with APFS.
