### ISSUE TITLE
add support for Big Sur

### ISSUE THREAD

**Issue by dspolleke** [geerlingguy/macos-virtualbox-vm#80]
I have tested manually to create a virtualbox-based vm. and it works. The script does not accomodate for it. 

May create PR to add it.

**Comment by dspolleke** [comment]
Well a lot of code could be replaced with:

`
installerAppName=(find /Applications -name "Install OS X *.app" )
isoName=$(basename ${installerAppName} | sed -e 's/Install OS X //g' -e 's/ /_/g' -e s/.app/.iso/g)
`
It will look up any available OS X installers and will create a isoName variable. 
It will work on any name you throw at it as long as Apple keeps the "Install OS X " part.

**Comment by addynaik** [comment]
i modified the script for Big Sur

https://gist.github.com/addynaik/1ba5e1c4a4ddd962f71ada2fdaf97375
